#!/usr/bin/env python3
"""
Multi-Process Data Ingestion for PostgreSQL Logical Replication Testing

Inserts data into the 'ingest_data' table:
    CREATE TABLE ingest_data (
        id BIGSERIAL PRIMARY KEY,           -- Auto-generated
        payload TEXT,                        -- Inserted by this script
        big_payload TEXT,                    -- Inserted by this script (1 KB)
        created_at TIMESTAMP DEFAULT now()   -- Auto-generated
    );

This script only inserts 'payload' and 'big_payload' columns.
The 'id' and 'created_at' columns are auto-generated by PostgreSQL.

Usage:
    export PGPASSWORD='your_password'
    python muiltiIngest.py
"""

import os
import time
import math
import psycopg2
from multiprocessing import Process
from psycopg2.extras import execute_values

# =============================================================================
# CONFIGURATION
# =============================================================================

HOST = "pg-source2-westus2.postgres.database.azure.com"
DBNAME = "pub"
USER = "postgres"
PASSWORD = os.getenv("PGPASSWORD")  # Set via: export PGPASSWORD='your_password'
PORT = 5432

# Workload parameters
TOTAL_RECORDS = 10_000_000  # Total rows to insert (10 million)
WORKERS = 16                # Parallel workers (16 concurrent processes)
BATCH_SIZE = 20_000         # Rows per INSERT statement per worker
SLEEP_SECONDS = 0           # Optional pause between batches (0 = no pause)

# Data payload size
BIG_TEXT = "X" * 1000       # 1 KB per row in big_payload column

# SQL statement - only inserts payload and big_payload
# id and created_at are auto-generated by PostgreSQL
INSERT_SQL = """
INSERT INTO ingest_data (payload, big_payload)
VALUES %s
"""

def worker_insert(worker_id: int, start_id: int, end_id: int):
    """
    Worker process that inserts a range of records into ingest_data table.

    Each row contains:
    - payload: "data_{i}" where i is the record number
    - big_payload: 1 KB of 'X' characters

    The id and created_at columns are auto-generated by PostgreSQL.
    """
    conn = psycopg2.connect(
        dbname=DBNAME,
        user=USER,
        password=PASSWORD,
        host=HOST,
        port=PORT,
        sslmode="require",  # Azure typically requires SSL
    )
    conn.autocommit = False
    cur = conn.cursor()

    print(f"[Worker {worker_id}] Inserting range {start_id}..{end_id - 1}")

    inserted = 0
    t0 = time.time()

    for batch_start in range(start_id, end_id, BATCH_SIZE):
        batch_end = min(batch_start + BATCH_SIZE, end_id)

        # Build rows for this batch
        # Only payload and big_payload - id and created_at are auto-generated
        rows = [(f"data_{i}", BIG_TEXT) for i in range(batch_start, batch_end)]

        # Fast multi-row insert using execute_values
        execute_values(
            cur,
            INSERT_SQL,
            rows,
            page_size=len(rows)  # one big VALUES list per batch
        )

        conn.commit()
        inserted += (batch_end - batch_start)

        if inserted % (BATCH_SIZE * 5) == 0:
            elapsed = time.time() - t0
            rate = inserted / elapsed if elapsed > 0 else 0
            print(f"[Worker {worker_id}] Inserted {inserted} rows | ~{rate:,.0f} rows/sec")

        if SLEEP_SECONDS > 0:
            time.sleep(SLEEP_SECONDS)

    cur.close()
    conn.close()
    print(f"[Worker {worker_id}] Done.")

def main():
    if PASSWORD is None:
        raise RuntimeError("Set PGPASSWORD env var: export PGPASSWORD='your_password'")

    # Split TOTAL_RECORDS across workers
    chunk = math.ceil(TOTAL_RECORDS / WORKERS)
    procs = []

    for w in range(WORKERS):
        start_id = w * chunk
        end_id = min((w + 1) * chunk, TOTAL_RECORDS)
        if start_id >= end_id:
            break

        p = Process(target=worker_insert, args=(w, start_id, end_id))
        p.start()
        procs.append(p)

    for p in procs:
        p.join()

    print("All workers finished.")

if __name__ == "__main__":
    main()
